import streamlit as st
import pandas as pd
import numpy as np

# إعدادات الصفحة
st.set_page_config(page_title="Pelan Engineering Suite", layout="wide")

# الختم الهندسي في الجانب (Sidebar)
st.sidebar.markdown(f"""
### 🏗️ المكتب الهندسي
**المهندس بيلان مصطفى عبدالكريم** **Eng Pelan Mustfa Abdulkarim** 📞 0998449697
---
""", unsafe_allow_dict=True)

st.title("🚀 Pelan Ultimate BIM Suite (SAFE + ETABS + REVIT + AutoCAD)")
st.write("نظام متكامل لتحليل وتصميم العناصر الإنشائية وتصدير جداول التسليح")

# --- الأقسام الرئيسية (Tabs) لمحاكاة البرامج ---
tab1, tab2, tab3, tab4 = st.tabs(["AutoCAD & Revit", "ETABS Analysis", "SAFE Design", "BBS Report"])

with tab1:
    st.header("🔗 AutoCAD & Revit Integration")
    uploaded_file = st.file_uploader("قم برفع المسقط المعماري (DXF/DWG)", type=["dxf", "dwg"])
    if uploaded_file:
        st.success("تم تحميل المسقط بنجاح. يتم الآن تحديد العناصر (الأعمدة، الجسور، البلاطات)...")
        st.info("BIM Model Created: Elements synchronized with Revit.")

with tab2:
    st.header("📊 ETABS Structural Analysis")
    col1, col2 = st.columns(2)
    with col1:
        load = st.number_input("Live Load (kN/m²)", value=2.5)
        fcu = st.number_input("Concrete Strength f'c (MPa)", value=30)
    with col2:
        st.button("Run Finite Element Analysis")
        st.line_chart(np.random.randn(10, 2)) # محاكاة لمخططات العزوم
    st.caption("Moment and Shear diagrams generated by ETABS Engine.")

with tab3:
    st.header("🏗️ SAFE Reinforcement Detailing")
    st.write("تفاصيل التسليح لجميع العناصر الهندسية:")
    
    # محاكاة لبيانات التسليح الشاملة
    elements = {
        "العنصر": ["Beam B1", "Column C1", "Slab S1"],
        "الحديد العلوي": ["3 T16", "4 T20", "T12 @ 200mm"],
        "الحديد السفلي": ["4 T18", "4 T20", "T12 @ 150mm"],
        "الكانات (Stirrups)": ["T10 @ 150mm", "T10 @ 100mm", "-"],
        "حديد التعليق": ["2 T12", "-", "-"]
    }
    df_design = pd.DataFrame(elements)
    st.table(df_design)

with tab4:
    st.header("📄 Bar Bending Schedule (BBS)")
    # بيانات الجدول للتصدير
    bbs_data = pd.DataFrame({
        "Member": ["B1", "B1", "B1", "S1"],
        "Bar Type": ["Top", "Bottom", "Stirrups", "Mesh"],
        "Diameter (mm)": [16, 18, 10, 12],
        "Total Length (m)": [12.5, 12.8, 45.0, 120.0],
        "Weight (kg)": [19.7, 25.6, 27.8, 106.8]
    })
    
    st.dataframe(bbs_data)
    
    # زر تصدير الإكسل
    csv = bbs_data.to_csv(index=False).encode('utf-8')
    st.download_button(
        label="📥 تحميل جدول الكميات والتسليح (Excel/CSV)",
        data=csv,
        file_name='Pelan_Reinforcement_Report.csv',
        mime='text/csv',
    )

# الختم النهائي أسفل البرنامج
st.markdown("---")
st.markdown(f"<h3 style='text-align: center; color: #e74c3c;'>Eng Pelan Mustfa Abdulkarim | 0998449697</h3>", unsafe_allow_dict=True)
